### ISSUE TITLE
SSL support for libpq

### ISSUE THREAD

**Issue by mbernasocchi** [opengisch/OSGeo4A#13]
`../configure $MY_STD_CONFIGURE_FLAGS --without-readline --with-openssl`
`checking for CRYPTO_new_ex_data in -lcrypto... no`
`configure: error: library 'crypto' is required for OpenSSL`

HINTS:
http://stackoverflow.com/questions/2952572/building-openssl-on-android-ndk
http://pgolub.wordpress.com/2008/12/15/building-postgresql-client-library-using-mingw-under-winxp-sp3/
https://github.com/fries/android-external-openssl/

More Hints:
https://www.nixuopen.org/media/library/files/2011/05/racoon_for_android_compile_problems_and_resolutions.html
https://groups.google.com/forum/#!topic/android-ndk/DMftXJOCHsQ
http://android3.git.kernel.org/platform/external/openssl.git/
https://github.com/fries/android-external-openssl/blob/master/README.android
https://groups.google.com/forum/#!msg/android-ndk/dM70p9b-yBk/C2ZMGE7aqd0J

**Comment by mbernasocchi** [comment]
`D/dalvikvm( 1972): Trying to load lib /data/data/org.qgis.qgis/lib/libpq.so 0x40791a90
W/System.err( 1972): java.lang.reflect.InvocationTargetException
W/System.err( 1972):     at java.lang.reflect.Method.invokeNative(Native Method)
W/System.err( 1972):     at java.lang.reflect.Method.invoke(Method.java:491)
W/System.err( 1972):     at org.kde.necessitas.origo.QtActivity.loadApplication(QtActivity.java:144)
W/System.err( 1972):     at org.kde.necessitas.origo.QtActivity.access$200(QtActivity.java:77)
W/System.err( 1972):     at org.kde.necessitas.origo.QtActivity$3$1$1.run(QtActivity.java:201)
W/System.err( 1972):     at android.os.Handler.handleCallback(Handler.java:587)
W/System.err( 1972):     at android.os.Handler.dispatchMessage(Handler.java:92)
W/System.err( 1972):     at android.os.Looper.loop(Looper.java:132)
W/System.err( 1972):     at android.app.ActivityThread.main(ActivityThread.java:4123)
W/System.err( 1972):     at java.lang.reflect.Method.invokeNative(Native Method)
W/System.err( 1972):     at java.lang.reflect.Method.invoke(Method.java:491)
W/System.err( 1972):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:841)
W/System.err( 1972):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:599)
W/System.err( 1972):     at dalvik.system.NativeStart.main(Native Method)
W/System.err( 1972): Caused by: java.lang.UnsatisfiedLinkError: Cannot load library: reloc_library[1315]:    87 cannot locate 'ENGINE_load_private_key'...
W/System.err( 1972):     at java.lang.Runtime.load(Runtime.java:390)
W/System.err( 1972):     at java.lang.System.load(System.java:534)
W/System.err( 1972):     at org.kde.necessitas.industrius.QtNative.loadBundledLibraries(QtNative.java:116)
W/System.err( 1972):     at org.kde.necessitas.industrius.QtActivityDelegate.loadApplication(QtActivityDelegate.java:156)
W/System.err( 1972):     ... 14 more`

**Comment by mbernasocchi** [comment]
cool :)
